### ISSUE TITLE
Unable to generate a proper pdf file

### ISSUE THREAD

**Issue by ldash** [repocad/lib#2]
when clicking the "PRINT (PDF)" button: a pdf file is generated, but containing only a single horizontal line...
See http://repocad.com/editor.html#HousePlan to reproduce...

Thanks.

**Comment by Jegp** [comment]
Thanks for picking this up! I'll get to it tomorrow :-)

**Comment by Jegp** [comment]
I found the bug; We've been playing with fonts and better rendering for fonts. But aparently the library we use to export PDF files didn't support fonts in the way we thought it did. I've added some better error handling and fixed the issues. Unfortunately we reverted to the default font, but we'll look into fixing this in the future. Thanks again for pointing to this and please let me know if you have further issues.

**Comment by Jegp** [comment]
Pdf printing is broken again...

**Comment by Jegp** [comment]
Fixed! There was a hard cast to a CanvasPrinter in the view - screwed things up for the PdfPrinter. My apologies for the bad coding practices ;-)
