### ISSUE TITLE
It would be really nice to have the zoom-in and zoom-out buttons/controls within the canvas area

### ISSUE THREAD

**Issue by ldash** [repocad/lib#3]
if it's not too difficult that is.
I admit, I'm currently handicapped by not having the scrolling functionality on my laptop and so I'm unable to zoom in (and out) on the canvas.
Thanks.

**Comment by Jegp** [comment]
Not hard at all. We've actually wondered what more controls to have in there. I'll look at it tomorrow.

**Comment by Jegp** [comment]
There's a prototype up now for zooming functionality. The UI still needs some work (I noticed it's still quite sluggish), but I hope this helps you for now. The rest will be put in the pipeline :-)
